--global value

GAME_STATUS_START   = "GAME_STATUS_START"
GAME_STATUS_END     = "GAME_STATUS_END"
GAME_STATUS_ROLLING = "GAME_STATUS_ROLLING"

TIME_PER_GAME = 60

BET_TYPE = {
    ONE = "ONE",
    TWO = "TWO",
    THREE = "THREE",
    FOUR = "FOUR",
    SIX = "SIX",
    ROW = "ROW",
    GROUP = "GROUP",
    RED_BLACK = "RED_BLACK",
    ODD_EVEN = "ODD_EVEN",
    BIG_SMALL = "BIG_SMALL",
}

BET_RATE           = {}
BET_RATE.ONE       = 36
BET_RATE.TWO       = 18
BET_RATE.THREE     = 12
BET_RATE.FOUR      = 9
BET_RATE.SIX       = 6
BET_RATE.ROW       = 3
BET_RATE.GROUP     = 3
BET_RATE.RED_BLACK = 2
BET_RATE.ODD_EVEN  = 2
BET_RATE.BIG_SMALL = 2

GREEN_NUM = {0} --绿色
RED_NUM   = {1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36} --红色
BLACK_NUM = {2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35} --黑色
